import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { BlogShell } from "./blog-shell";
import { getPublicPosts } from "./posts";

export const metadata:Metadata={title:"Insights & Company News",description:"Royal Horizon insights, company updates, case studies and practical guidance for institutions across Malawi.",alternates:{canonical:"/blog"}};
export default async function BlogPage(){const posts=await getPublicPosts();return <BlogShell><section className="relative overflow-hidden border-b border-stone-200 bg-white"><div className="absolute inset-0 opacity-[0.055] [background-image:url('/brand/african-pattern-brown.jpeg')] [background-size:520px]"/><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-600">Royal Horizon journal</p><h1 className="mt-4 max-w-3xl font-[family-name:var(--font-sora)] text-4xl font-bold tracking-tight sm:text-6xl">Ideas that help organisations move forward.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Company news, practical procurement guidance, technology thinking and stories from our work across Malawi.</p></div></section><section className="mx-auto max-w-7xl px-6 py-16 lg:px-8">{posts.length?<div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{posts.map(post=><Link href={`/blog/${post.slug}`} key={post.id} className="group overflow-hidden rounded-[1.75rem] border border-stone-200 bg-white shadow-[0_14px_40px_rgba(55,45,36,.07)] transition hover:-translate-y-1 hover:shadow-[0_20px_55px_rgba(55,45,36,.12)]"><div className="relative aspect-[16/10] overflow-hidden bg-orange-50">{post.cover_image_url?<Image src={post.cover_image_url} alt={post.title} fill unoptimized sizes="(max-width:768px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105"/>:<div className="absolute inset-0 opacity-20 [background-image:url('/brand/african-pattern-brown.jpeg')] [background-size:360px]"/>}</div><div className="p-6"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-orange-600">{post.content_type.replaceAll("_"," ")}</p><h2 className="mt-3 text-xl font-bold leading-snug">{post.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{post.excerpt||post.body.slice(0,180)}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Read article <ArrowUpRight className="size-4"/></span></div></Link>)}</div>:<div className="rounded-3xl border border-dashed border-stone-300 bg-white p-14 text-center"><h2 className="text-xl font-bold">Our first articles are being prepared.</h2><p className="mt-2 text-slate-500">Please check back soon for Royal Horizon updates and practical insights.</p></div>}</section></BlogShell>}
