import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { BlogShell } from "../blog-shell";
import { getPublicPost } from "../posts";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const post=await getPublicPost(slug);if(!post)return{title:"Article not found"};const description=post.excerpt||post.body.slice(0,155);return{title:post.title,description,alternates:{canonical:`/blog/${post.slug}`},openGraph:{type:"article",title:post.title,description,images:post.cover_image_url?[post.cover_image_url]:["/opengraph-image"]}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const post=await getPublicPost(slug);if(!post)notFound();const paragraphs=post.body.split(/\n\s*\n/).filter(Boolean);const articleSchema={"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,image:post.cover_image_url,datePublished:post.published_at,author:{"@type":"Organization",name:"Royal Horizon Limited"},publisher:{"@type":"Organization",name:"Royal Horizon Limited",logo:{"@type":"ImageObject",url:"https://www.royalhorizonmw.com/rh-logo-orange-cropped.png"}}};return <BlogShell><article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema).replace(/</g,"\\u003c")}}/><div className="mx-auto max-w-4xl px-6 pb-8 pt-12"><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-orange-600"><ArrowLeft className="size-4"/>All insights</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.2em] text-orange-600">{post.content_type.replaceAll("_"," ")}</p><h1 className="mt-4 font-[family-name:var(--font-sora)] text-4xl font-bold leading-tight tracking-tight sm:text-6xl">{post.title}</h1>{post.excerpt&&<p className="mt-6 text-xl leading-8 text-slate-600">{post.excerpt}</p>}<p className="mt-5 text-sm text-slate-500">Royal Horizon Limited{post.published_at?` · ${new Intl.DateTimeFormat("en-MW",{dateStyle:"long"}).format(new Date(post.published_at))}`:""}</p></div>{post.cover_image_url&&<div className="relative mx-auto aspect-[16/8] max-w-6xl overflow-hidden rounded-[2rem]"><Image src={post.cover_image_url} alt={post.title} fill unoptimized priority sizes="100vw" className="object-cover"/></div>}<div className="mx-auto max-w-3xl px-6 py-14">{paragraphs.map((paragraph,index)=><p key={index} className="mb-6 text-lg leading-8 text-slate-700">{paragraph}</p>)}</div></article></BlogShell>}
